### PR TITLE
Considered Byte Order Mark when processing metadata.

### PR DESCRIPTION
**Pull request by dirivero**
This fixes issue #7.

### CODE REVIEW

**Comment by ryanlelek** [comment]
Thank you.
Can you please add a test to `tests/raneto.js` on the appropriate method?

**Comment by dirivero** [comment]
Added a test and a sample file starting with BOM in the sample test content folder.

**Comment by ryanlelek** [comment]
Thanks for doing that.
Unfortunately, 1 test failed as a result of the update.

" #doSearch()
  1) returns an array of search results
expected [an array]  to have a length of 2 but got 3"

Everything seems to be working correctly, including your patch, and it looks like adding the new file caused the count to go up by 1. So once that test is updated and passed, we're good to go (run on your local machine with make test)

More details here: https://travis-ci.org/gilbitron/Raneto-Core/builds/107120877

**Comment by ryanlelek** [comment]
Thank you!

**Pull request merged**
