### PR TITLE
es6 migration

### PR DESCRIPTION
**Pull request by pmoleri**
This branch migrates Raneto-Core source code to ES6 (ES2015).

The code gets transpiled from src/ to lib/ making it compatible con ES5 and node 0.10.
The transpile process executes before test, install and publish.
So published to npm packages will only contains the es5 code.

With this change Raneto-Core is written as a class, the module exports a default instance, but in the future the class itself could be exported or a `newInstance` method, to enable the use of multiple instances in the same application. For example serve content from multiple base folders, each one backed by a Raneto-Core instance.

### CODE REVIEW

**Comment by ryanlelek** [comment]
Hi Pablo,
Thanks for the detailed description (I needed it!)

All good. Merging in and will edit `package.json` and `Makefile` to be compatible with your changes

**Comment by ryanlelek** [comment]
Ok, so v0.5.1 was published without ES2015, and v0.6.0 will be published with ES2015.

Let me know if the filepaths in package.json give you any issues on Windows
(Reason I use local versions and don't install things globally is because with all the projects and Node versions I run through, it can get really confusing with global modules)

**Comment by pmoleri** [comment]
It does fail on Windows: 
> '.' is not recognized as an internal or external command, operable program or batch file.

I guess that the first slash acts as a delimiter.

Anyway, I think the version I pushed should work correctly. As far as I know, at least for some time now, scripts run via `npm run` will pickup the local versions of the dependencies, e.g. babel and jshint. It adds every cli-executable to `node_modules/.bin/ ` and adds that folder at the begining of your `path`, so `npm run compile` should run `node_modules/.bin/babel` and not a global command.

It also appeared to working properly in travis-ci.
Could you try go back to the non-prefixed paths? I think it is how npm intends scripts to work.

**Comment by ryanlelek** [comment]
Yeah `./` is a force of explicit Unixy habit.
I can confirm without the prefix works, so if removing the prefix fixes it on Windows, then we have our solution

**Comment by ryanlelek** [comment]
Updated

**Comment by pmoleri** [comment]
Great it worked!

**Pull request merged**
